spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

flyway:
  enabled: true
  locations: classpath:db/migration